services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - /share/Container/containerapp/sonarr/data:/config # Config files
      - /share/Media/TV:/tv # TV series location with shared mount flag :shared
      - /share/Public/Incomplete:/downloads     # Completed downloads location with shared mount flag :shared
    ports:
      - 8989:8989
    restart: unless-stopped