services:
  filebot:
    image: rednoah/filebot:latest
    container_name: filebot
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
      - UMASK=000                          # Set permissive umask to help with permission issues
      - SKIP_CHOWN=true                    # Skip ownership change operations
    volumes:
      - /share/Container/containerapp/filebot:/config # Config files
      - /share/Multimedia/movies:/movies #optional
      - /share/Multimedia/tv:/tv #optional
    ports:
      - 9696:9696
    restart: unless-stopped
    privileged: true  
    networks:
      - default
      - shared_network
networks:
  default:
    driver: bridge
  shared_network:
    name: app_network                     # Running in privileged mode