services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - /share/Container/containerapp/heimdall:/config # Config files
    ports:
      - 8081:80
      - 4431:443
    restart: unless-stopped
