services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
      - UMASK=000                          # Set permissive umask to help with permission issues
      - SKIP_CHOWN=true                    # Skip ownership change operations
    volumes:
      - /share/Container/containerapp/readarr/data:/config
      - /share/Multimedia/eBook:/ebooks #optional
      - /share/Multimedia/aBook:/abooks #optional
      - /share/Public/Incomplete:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
    privileged: true                       # Running in privileged mode
    networks:
      - default
      - shared_network
networks:
  default:
    driver: bridge
  shared_network:
    name: app_network                     # Running in privileged mode