services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly-0.4.19.2811-ls400
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
      - UMASK=002                          # Group-writable files without world-write permissions
      - SKIP_CHOWN=true                    # Skip ownership change operations
    volumes:
      - /share/Container/containerapp/readarr/data:/config
      - /share/Multimedia/eBook:/ebooks #optional
      - /share/Multimedia/aBook:/abooks #optional
      - /share/Public/Complete:/downloads/complete #optional
      #- /share/Public/Complete:/downloads #optional
      #- /share/Public/Incomplete:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - default
      - shared_network
networks:
  default:
    driver: bridge
  shared_network:
    name: app_network
    external: true
