services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Sydney
      - UMASK=000                          # Set permissive umask to help with permission issues
      - SKIP_CHOWN=true                    # Skip ownership change operations
    volumes:
      - /share/Container/containerapp/sonarr/data:/config # Config files
      - /share/Multimedia/TV:/tv # TV series location with shared mount flag :shared
      #- /share/Public/Incomplete:/downloads     # Completed downloads location with shared mount flag :shared
      - /share/Public/Complete/tv-sonarr:/downloads/complete/tv-sonarr #where transmission stores completed downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    privileged: true                       # Running in privileged mode
    networks:
      - default
      - shared_network
networks:
  default:
    driver: bridge
  shared_network:
    name: app_network